<center><h1> Série de Travaux Pratiques N° 7 - Machine Learning </h1></center>
<center><h2> K-Nearest Neighbor and Decision Tree</h2></center>

---



Pour ce TP, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

# **Partie I : K-Nearest Neighbor**

In [ ]:
# IRIS Dataset : KNN


# 1- Importer les packages nécessaires

# 2- Lire l'ensemble de données dans le dataframe pandas

# 3- Afficher et explorer l'ensemble de données "**iris.csv**"

# 4- Extraire les variables d'entrée X

# 5- Extraire les variables de sortie y

# 6- Diviser le dataset en Train / Test

# 7- Mise à l'échelle des fonctionnalités avec Transform()

# 8- Définir votre modèle KNN

# 9- Entraîner le modèle

# 10- Prédiction sur l'ensemble de test

# 11- Évaluation du modèle à l'aide de métriques

#12- Changer le K = {5, 10, 20, 30, 40}, que remarquez-vous?

# **Questions :**

1- Importer les packages nécessaires

2- Lire l'ensemble de données dans le dataframe pandas

3- Afficher et explorer l'ensemble de données "**iris.csv**"

4- Extraire les variables d'entrée X

5- Extraire les variables de sortie y

6- Diviser le dataset en Train / Test

7- Mise à l'échelle des fonctionnalités avec Transform()

8- Définir votre modèle **KNN**

9- Entraîner le modèle

10- Prédiction sur l'ensemble de test

11- Évaluation du modèle à l'aide de métriques

In [2]:
#1-2-3-4
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
data = pd.read_csv('iris.csv')
print(data.head())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


In [5]:
#4-Extraire les variables d'entrée X
data = pd.read_csv('iris.csv')
X= data.values[:,:-1]
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
#5-Extraire les variables d'entrée Y
data = pd.read_csv('iris.csv')
Y= data.values[:,-1]
Y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [10]:
from sklearn.model_selection import train_test_split
#6- Diviser les données
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [34]:
 #7-Mise à l'échelle des fonctionnalités avec Transform()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scale.fit_transform(X_train)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [54]:
#8- Définir votre modèle KNN
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)

In [55]:
#9-Entraîner le modèle
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [56]:
#10- Prédiction sur l'ensemble de test
Y_pred_knn=knn.predict(X_test)

In [57]:
#11- Évaluation du modèle à l'aide de métriques
from sklearn.metrics import classification_report, accuracy_score
from sklearn import metrics 

accuracy=accuracy_score(Y_test,Y_pred_knn)
print(classification_report(Y_test,Y_pred_knn))
print(f"accuracy:,{accuracy*100:.2f}%")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

accuracy:,100.00%


# **Partie II : Decision Trees**

# **Questions :**

1- Importer les packages nécessaires

2- Lire l'ensemble de données dans le dataframe pandas

3- Afficher et explorer l'ensemble de données "**iris.csv**"

4- Extraire les variables d'entrée X

5- Extraire les variables de sortie y

6- Diviser le dataset en Train / Test

7- Mise à l'échelle des fonctionnalités avec Transform()

8- Définir votre modèle **Decision Tree**

9- Entraîner le modèle

10- Prédiction sur l'ensemble de test

11- Évaluation du modèle à l'aide de métriques

In [61]:
# IRIS Dataset : Decision Tree


# 1- Importer les packages nécessaires
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# 2- Lire l'ensemble de données dans le dataframe pandas
data= pd.read_csv('iris.csv')
# 3- Afficher et explorer l'ensemble de données "iris.csv"
print (data.head())
# 4- Extraire les variables d'entrée X
data = pd.read_csv('iris.csv')
X= data.values[:,:-1]
X
# 5- Extraire les variables de sortie y
data = pd.read_csv('iris.csv')
Y= data.values[:,-1]
Y
# 6- Diviser le dataset en Train / Test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
# 7- Mise à l'échelle des fonctionnalités avec Transform()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
# 8- Définir votre modèle KNN
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
# 9- Entraîner le modèle
dt.fit(X_train, Y_train)
# 10- Prédiction sur l'ensemble de test
Y_pred = dt.predict(X_test)
# 11- Évaluation du modèle à l'aide de métriques
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print (confusion_matrix(Y_test,Y_pred))
print (classification_report(Y_test, Y_pred))
print (accuracy_score(Y_test, Y_pred)*100)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       1.00      1.00      1.00         9
   Virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

100.0
